### ISSUE TITLE
Durée de vie de cette base ?

### ISSUE THREAD

**Issue by laowantong** [Lyokolux/mot_croises#1]
Tu es aussi bon camarade que bon étudiant :smiley:

Le but de ces mots croisés étant de vous inciter à vous plonger dans le cours, je te demanderai juste de fermer ton dépôt à la fin de l'année universitaire: car le même outil avec lequel tu aides à réviser les étudiants de cette année, risque de se retourner contre ceux de l'an prochain (il est tentant de le transformer pour afficher bêtement les solutions).

Bravo en tout cas pour ton travail !

**Comment by Lyokolux** [comment]
Le dépôt sera bien fermé en fin d'année.
