### ISSUE TITLE
Problème d'alignement pour les derniers mots croisés?

### ISSUE THREAD

**Issue by laowantong** [Lyokolux/mot_croises#4]
Lors d'un test, j'ai obtenu ceci:
```
Les éléments d'une liste, comme ceux d'un tuple, sont séparés par des ____
>>> 
Solutions are : TABLEAU DIRECT
```
La réponse devrait être: `VIRGULES`.

**Comment by Lyokolux** [comment]
Effectivement, une erreur bête : deux oubli de virgules pour séparer 3 phrases dans la liste

**Comment by laowantong** [comment]
C'est précisément pour ça que je considère la concaténation automatique des chaînes comme une bogue, et non une fonctionnalité de Python.

**Comment by laowantong** [comment]
Pro tip: quand tu pousses un commit, tu peux automatiquement fermer l'issue correspondante en incluant dans ton message son numéro de la façon suivante: "Fix #3". Cela permet aussi de référencer automatiquement la révision dans la page de l'issue.
